language: generic

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.49.2/hugo_extended_0.49.2_Linux-64bit.deb
  - echo "18d898ad7dbc61f8dccda14d102dad4cdcfc46acb4bc849a369219102e26c1db hugo_extended_0.49.2_Linux-64bit.deb" | sha256sum -c - || exit 1;
  - sudo dpkg -i hugo_extended_0.49.2_Linux-64bit.deb

install:
  - hugo env
  - hugo
